# Arabic {{{1 #
arabic = {
        # Basic functions {{{2 #
        'اطبع': 'print',
        'لكل': 'for',
        'فى': 'in',
        'في': 'in',
        'مدى': 'range',
        'مدي': 'range',
        'اذا': 'if',
        'الا': 'elif',
        'اخر': 'else',
        # 2}}} #
        # String methods {{{2 #
        'نص': 'string',
        'تكبير_اول_حرف': 'capitalize',
        'تصغير_طى': 'casefold',
        'تصغير_طي': 'casefold',
        'توسيط': 'center',
        'عد': 'count',  # Also part of the List methods
        'ترميز': 'encode',
        'نهايته': 'endswith',
        'توسيع_التبويب': 'expandtabs',
        'ايجاد': 'find',
        'صيغة': 'format',
        'خريطة_صياغة': 'format_map',
        'فهرسة': 'index',  # ُAlso part of the lists methods
        'ابجدي_رقمي_جميعهم': 'isalnum',
        'ابجدي_رقمى_جميعهم': 'isalnum',
        'حروف_جميعهم': 'isalpha',
        'اسكي_جميعهم': 'isascii',
        'اسكى_جميعهم': 'isascii',
        'كسر_عشري_جميعهم': 'isdecimal',
        'كسر_عشرى_جميعهم': 'isdecimal',
        'رقمي_جميعهم': 'isdigit',
        'رقمى_جميعهم': 'isdigit',
        'معرف': 'isidentifier',
        'احرف_صغيرة': 'islower',
        'رقمى': 'isnumeric',
        'ىقمي': 'isnumeric',
        'للطباعة': 'isprintable',
        'فارغ': 'isspace',
        'عنوان': 'istitle',
        'احرف_كبيرة': 'isupper',
        'ضم': 'join',
        'ضبط_لليسار': 'ljust',
        'تصغير': 'lower',
        'قطع_لليسار': 'lstrip',
        'صنع_ترجمة': 'maketrans',
        'تقسيم': 'partition',
        'استبدال': 'replace',
        'المكان_في_النص': 'rfind',
        'الترتيب_في_النص': 'rindex',
        'ضبط_لليمين': 'rjust',
        'ر_تقسيم': 'rpartition',
        'ر_فصل': 'rsplit',
        'قطع_لليمين': 'rstrip',
        'فصل': 'split',
        'فصل_سطور': 'splitlines',
        'يبدا_مع': 'startswith',
        'قطع': 'strip',
        'عكس_التكبير': 'swapcase',
        'عنونة': 'title',
        'ترجمة': 'translate',
        'تكبير': 'upper',
        'ز_ملئ': 'zfill',
        # 2}}} #
        # List Methods {{{2 #
        'قائمة': 'list',
        'تضمين': 'append',
        'محو': 'clear',  # Also part of the Dictionary Methods
        'نسخ': 'copy',  # Also part of the Dictionary Methods
        'عد': 'count',
        'المد': 'extend',
        'إضافة': 'insert',
        'رمى': 'pop',  # Also part of the Dictionary Methods
        'رمي': 'pop',
        'حذف': 'remove',
        'عكس': 'reverse',
        'ترتيب': 'sort',
        # 2}}} #
}
# 1}}} #
