# Arabic {{{1 #
arabic = {
        # Basic Orders
        'اطبع': 'print',
        'لكل': 'for',
        'فى': 'in',
        'مدى': 'range',
        'اذا': 'if',
        'الا': 'elif',
        'اخر': 'else',
        # String Methods 
        'تكبير_اول_حرف()': 'capitalize()',
        'تصغير()':'casefold()',               
        'توسيط()': 'center()',	              
        'عد()':'count()',	                
        'ترميز()':'encode()',	                
        'نهايته()':'endswith()',	        
        'توسيع_التبويب()':'expandtabs()',      
        'ايجاد()':'find()',	                
        'صيغة()':'format()',	                
        'خريطة_صياغة()':'format_map()',	       
        'فهرسة()':'index()',                    
        'ابجدي_رقمي_جميعهم()':'isalnum()',     
        'حروف_جميعهم()':'isalpha()',	       
        'اسكي_جميعهم()':'isascii()',	       
        'كسر_عشري_جميعهم()':'isdecimal()',	
        'رقمي_جميعهم()':'isdigit()',	        
        'معرف()':'isidentifier()',	         
        'احرف_صغيرة()':'islower()',	         
        'رقمي()':'isnumeric()',	                
        'للطباعة()':'isprintable()',	        
        'فارغ()':'isspace()',	                       
        'عنوان()':'istitle()',	                       
        'احرف_كبيرة()':'isupper()',	               
        'ضم()':'join()',	                        
        'ضبط_لليسار()':'ljust()',	                        
        'تصغير()':'lower()',	                        
        'قطع_لليسار()':'lstrip()',	                
        'صنع_ترجمة()':'maketrans()',	                
        'تقسيم()':'partition()',	                
        'استبدال()':'replace()',	                       
        'المكان_في_النص()':'rfind()',	                       
        'الترتيب_في_النص()':'rindex()',	                       
        'ضبط_لليمين()':'rjust()',	                       
        'ر_تقسيم()':'rpartition()',	                        
        'ر_فصل()':'rsplit()',	                        
        'قطع_لليمين()':'rstrip()',	                
        'فصل()':'split()',	                        
        'فصل_سطور()':'splitlines()',	                
        'يبدا_مع()':'startswith()',	                
        'قطع()':'strip()',	                        
        'عكس_التكبير()':'swapcase()',	               
        'عنونة()':'title()',   	
        'ترجمة()':'translate()',
        'تكبير()':'upper()',	
        'ز_ملئ()':'zfill()',	
        }
# 1}}} #
